"""Generate professional PDF resumes from structured data."""
from fpdf import FPDF
from datetime import datetime


def _safe(text: str) -> str:
    """Sanitize text for fpdf — replace non-Latin1 chars."""
    if not text:
        return ""
    return (text
        .replace("\u2013", "-")   # en dash
        .replace("\u2014", "-")   # em dash
        .replace("\u2018", "'")   # left single quote
        .replace("\u2019", "'")   # right single quote
        .replace("\u201c", '"')   # left double quote
        .replace("\u201d", '"')   # right double quote
        .replace("\u2026", "...")  # ellipsis
        .replace("\u00a0", " ")   # non-breaking space
        .encode("latin-1", errors="replace")
        .decode("latin-1")
    )


class ResumePDF(FPDF):
    """Custom PDF class with consistent styling."""

    PRIMARY = (245, 185, 66)  # #f5b942
    DARK = (30, 30, 30)
    GRAY = (100, 100, 100)
    LIGHT_GRAY = (200, 200, 200)
    WHITE = (255, 255, 255)
    SEVERITY_COLORS = {
        "urgent": (220, 50, 50),
        "severe": (230, 130, 50),
        "likely": (180, 180, 50),
    }

    def header(self):
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self.GRAY)
        self.cell(0, 10, f"Generated by ScholarshipRight | {datetime.now().strftime('%b %d, %Y')}", align="C")

    def section_title(self, title: str):
        """Draw a section header with gold underline."""
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*self.DARK)
        self.cell(0, 8, title.upper(), new_x="LMARGIN", new_y="NEXT")
        y = self.get_y()
        self.set_draw_color(*self.PRIMARY)
        self.set_line_width(0.6)
        self.line(self.l_margin, y, self.w - self.r_margin, y)
        self.ln(4)

    def body_text(self, text: str, bold: bool = False):
        """Multi-cell body text."""
        if not text:
            return
        text = _safe(text)
        self.set_font("Helvetica", "B" if bold else "", 10)
        self.set_text_color(*self.DARK)
        self.multi_cell(0, 5, text)
        self.ln(1)

    def label_value(self, label: str, value: str):
        """Inline label: value pair."""
        if not value:
            return
        label = _safe(label)
        value = _safe(str(value))
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*self.GRAY)
        lw = self.get_string_width(label + ": ") + 2
        self.cell(lw, 5, label + ": ")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.DARK)
        self.multi_cell(0, 5, value)
        self.ln(1)

    def bullet(self, text: str):
        """Bullet point item."""
        if not text:
            return
        text = _safe(text)
        x = self.get_x()
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.DARK)
        self.cell(6, 5, "|")
        self.multi_cell(0, 5, text)
        self.ln(0.5)


def generate_resume_pdf(resume: dict, mode: str = "cv") -> bytes:
    """Generate a professional PDF from resume data dict.
    
    mode: "resume" = single page, concise (no descriptions, key info only)
          "cv" = full detail, 1-2 pages with everything
    """
    concise = mode == "resume"
    pdf = ResumePDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Name & Contact ──
    name = _safe(resume.get("full_name", "Resume"))
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*pdf.DARK)
    pdf.cell(0, 12, name or "Resume", new_x="LMARGIN", new_y="NEXT")

    # Contact line
    contacts = []
    if resume.get("email"):
        contacts.append(_safe(resume["email"]))
    if resume.get("phone"):
        contacts.append(_safe(resume["phone"]))
    if resume.get("location"):
        contacts.append(_safe(resume["location"]))
    if contacts:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*pdf.GRAY)
        pdf.cell(0, 5, "  |  ".join(contacts), new_x="LMARGIN", new_y="NEXT")

    links = []
    if resume.get("linkedin_url"):
        links.append(f"LinkedIn: {_safe(resume['linkedin_url'])}")
    if resume.get("portfolio_url"):
        links.append(f"Portfolio: {_safe(resume['portfolio_url'])}")
    if links:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*pdf.PRIMARY)
        pdf.cell(0, 5, "  |  ".join(links), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # ── Summary ──
    if resume.get("summary"):
        pdf.section_title("Professional Summary")
        pdf.body_text(_safe(resume["summary"]))
        pdf.ln(2)

    # ── Education ──
    edu = resume.get("education", [])
    if edu:
        pdf.section_title("Education")
        for e in edu:
            degree_field = _safe(" ".join(filter(None, [e.get("degree"), e.get("field")])))
            inst = _safe(e.get("institution", ""))
            dates = _safe(" - ".join(filter(None, [e.get("start_date"), e.get("end_date")])))

            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 6, degree_field or inst, new_x="LMARGIN", new_y="NEXT")

            if degree_field and inst:
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, inst, new_x="LMARGIN", new_y="NEXT")

            if dates:
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, dates, new_x="LMARGIN", new_y="NEXT")

            if e.get("gpa") and not concise:
                pdf.label_value("GPA", _safe(str(e["gpa"])))
            if e.get("description") and not concise:
                pdf.body_text(_safe(e["description"]))
            pdf.ln(2)

    # ── Work Experience ──
    exp = resume.get("experience", [])
    if exp:
        pdf.section_title("Work Experience")
        for ex in exp:
            pos = _safe(ex.get("position", ""))
            company = _safe(ex.get("company", ""))
            dates = _safe(" - ".join(filter(None, [ex.get("start_date"), ex.get("end_date")])))

            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 6, pos, new_x="LMARGIN", new_y="NEXT")

            right_text = _safe(", ".join(filter(None, [company, ex.get("location")])))
            if right_text or dates:
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(*pdf.GRAY)
                parts = [right_text, dates]
                pdf.cell(0, 5, "  |  ".join(filter(None, parts)), new_x="LMARGIN", new_y="NEXT")

            if ex.get("description") and not concise:
                pdf.body_text(_safe(ex["description"]))
            for ach in ex.get("achievements", []):
                pdf.bullet(ach)
            pdf.ln(2)

    # ── Research / Projects ──
    projects = resume.get("research_projects", [])
    if projects:
        pdf.section_title("Research & Projects")
        for p in projects:
            ptype = _safe(p.get("type", "project").capitalize())
            title = _safe(p.get("title", ""))
            org = _safe(p.get("organization", ""))
            role = _safe(p.get("role", ""))
            dates = _safe(" - ".join(filter(None, [p.get("start_date"), p.get("end_date")])))

            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 6, f"[{ptype}] {title}", new_x="LMARGIN", new_y="NEXT")

            details = " | ".join(filter(None, [role, org, dates]))
            if details:
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, details, new_x="LMARGIN", new_y="NEXT")

            if p.get("technologies"):
                pdf.set_font("Helvetica", "I", 9)
                pdf.cell(0, 5, f"Tech: {p['technologies']}", new_x="LMARGIN", new_y="NEXT")

            if p.get("description"):
                pdf.body_text(_safe(p["description"]))
            if p.get("outcomes"):
                pdf.label_value("Outcomes", _safe(p["outcomes"]))
            if p.get("url"):
                pdf.label_value("URL", _safe(p["url"]))
            pdf.ln(2)

    # ── Skills ──
    skills = resume.get("skills", [])
    if skills:
        pdf.section_title("Skills")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*pdf.DARK)
        pdf.multi_cell(0, 5, " | ".join(skills))
        pdf.ln(3)

    # ── Languages ──
    langs = resume.get("languages", [])
    if langs:
        pdf.section_title("Languages")
        for lang in langs:
            name = _safe(lang.get("language", ""))
            prof = _safe(lang.get("proficiency", ""))
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(40, 5, name)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*pdf.GRAY)
            pdf.cell(0, 5, prof, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # ── Certifications ──
    certs = resume.get("certifications", [])
    if certs and not concise:
        pdf.section_title("Certifications")
        for c in certs:
            name = _safe(c.get("name", ""))
            issuer = _safe(c.get("issuer", ""))
            date = _safe(c.get("date", ""))
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 5, name, new_x="LMARGIN", new_y="NEXT")
            details = " | ".join(filter(None, [issuer, date]))
            if details:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, details, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # ── Publications ──
    pubs = resume.get("publications", [])
    if pubs and not concise:
        pdf.section_title("Publications")
        for p in pubs:
            pdf.bullet(_safe(p.get("title", "")))
            details = " | ".join(filter(None, [p.get("journal"), p.get("date")]))
            if details:
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(6, 5, "")
                pdf.cell(0, 5, details, new_x="LMARGIN", new_y="NEXT")
            if p.get("doi"):
                pdf.set_font("Helvetica", "", 8)
                pdf.cell(6, 5, "")
                pdf.cell(0, 5, f"DOI: {_safe(p['doi'])}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # ── Awards ──
    awards = resume.get("awards", [])
    if awards and not concise:
        pdf.section_title("Awards")
        for a in awards:
            name = _safe(a.get("name", ""))
            issuer = _safe(a.get("issuer", ""))
            date = a.get("date", "")
            details = " | ".join(filter(None, [issuer, date]))
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 5, name, new_x="LMARGIN", new_y="NEXT")
            if details:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, details, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # ── References ──
    refs = resume.get("ref_list", [])
    if refs and not concise:
        pdf.section_title("References")
        for r in refs:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 5, _safe(r.get("name", "")), new_x="LMARGIN", new_y="NEXT")
            if r.get("position"):
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, _safe(r["position"]), new_x="LMARGIN", new_y="NEXT")
            if r.get("contact"):
                pdf.set_font("Helvetica", "", 9)
                pdf.cell(0, 5, _safe(r["contact"]), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    return bytes(pdf.output())
