"""Generate professional PDF resumes from structured data.

Supports 4 layout themes: classic, modern, academic, compact.
Reads style preferences from resume['style'] dict.

NOTE: fpdf (v1) only supports Latin-1. Non-Latin-1 characters (CJK, Arabic,
Cyrillic, emoji) are replaced with '?' by _safe(). To support full Unicode,
migrate to fpdf2 with a Unicode TTF font.
"""
import logging
from fpdf import FPDF
from datetime import datetime

logger = logging.getLogger(__name__)


def _safe(text: str) -> str:
    """Sanitize text for fpdf — replace non-Latin1 chars."""
    if not text:
        return ""
    result = (text
        .replace("\u2013", "-")   # en dash
        .replace("\u2014", "-")   # em dash
        .replace("\u2018", "'")   # left single quote
        .replace("\u2019", "'")   # right single quote
        .replace("\u201c", '"')   # left double quote
        .replace("\u201d", '"')   # right double quote
        .replace("\u2026", "...")  # ellipsis
        .replace("\u00a0", " ")   # non-breaking space
        .replace("\u2022", "-")   # bullet •
        .replace("\u25cf", "-")   # filled circle ●
        .replace("\u25cb", "-")   # empty circle ○
        .encode("latin-1", errors="replace")
        .decode("latin-1")
    )
    if "?" in result and "?" not in text:
        logger.warning("PDF: non-Latin1 chars replaced in text: %s...", text[:80])
    return result


def _hex_to_rgb(hex_color: str) -> tuple:
    """Convert '#f5b942' to (245, 185, 66)."""
    h = hex_color.lstrip("#")
    if len(h) == 6:
        return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
    return (245, 185, 66)  # fallback gold


# ── Theme configs ─────────────────────────────────────────────────────
# Mirrors the frontend ThemeConfig in ResumePreview.tsx

_FONT_MAP = {
    "Helvetica, Arial, sans-serif": "Helvetica",
    "Georgia, serif": "Times",
    "'Times New Roman', serif": "Times",
    "Verdana, sans-serif": "Helvetica",
    "'Trebuchet MS', sans-serif": "Helvetica",
}

THEMES = {
    "classic": {
        "padding": 10,
        "section_gap": 6,
        "entry_gap": 3,
        "name_align": "L",
        "title_upper": True,
        "title_size": 13,
        "title_align": "L",
        "title_decoration": "underline",   # underline | bar | double | none
        "bullet_char": "|",
        "font_scale": 1.0,
        "entry_title_size": 11,
        "body_size": 10,
        "show_footer": True,
    },
    "modern": {
        "padding": 12,
        "section_gap": 8,
        "entry_gap": 4,
        "name_align": "L",
        "title_upper": False,
        "title_size": 12,
        "title_align": "L",
        "title_decoration": "bar",
        "bullet_char": "\u00b7",  # · middle dot (Latin-1 safe)
        "font_scale": 1.0,
        "entry_title_size": 11,
        "body_size": 10,
        "show_footer": False,
    },
    "academic": {
        "padding": 10,
        "section_gap": 5,
        "entry_gap": 2.5,
        "name_align": "C",
        "title_upper": True,
        "title_size": 12,
        "title_align": "C",
        "title_decoration": "double",
        "bullet_char": "-",  # dash (Latin-1 safe)
        "font_scale": 0.95,
        "entry_title_size": 10.5,
        "body_size": 9.5,
        "show_footer": True,
    },
    "compact": {
        "padding": 7,
        "section_gap": 3,
        "entry_gap": 2,
        "name_align": "L",
        "title_upper": True,
        "title_size": 11,
        "title_align": "L",
        "title_decoration": "underline",
        "bullet_char": "\u00b7",  # · middle dot (Latin-1 safe)
        "font_scale": 0.88,
        "entry_title_size": 10,
        "body_size": 9,
        "show_footer": False,
    },
}


class ResumePDF(FPDF):
    """Custom PDF class with theme-aware styling."""

    def __init__(self, theme: dict, primary_rgb: tuple, heading_font: str, body_font: str):
        super().__init__()
        self.theme = theme
        self.PRIMARY = primary_rgb
        self.DARK = (30, 30, 30)
        self.GRAY = (100, 100, 100)
        self.heading_font = heading_font
        self.body_font = body_font

    def header(self):
        pass

    def footer(self):
        if not self.theme.get("show_footer", True):
            return
        self.set_y(-15)
        self.set_font(self.body_font, "I", 8)
        self.set_text_color(*self.GRAY)
        self.cell(0, 10, f"Generated by ScholarshipRight | {datetime.now().strftime('%b %d, %Y')}", align="C")

    def section_title(self, title: str):
        """Draw a section header with theme-appropriate decoration."""
        t = self.theme
        font_size = round(t["title_size"] * t["font_scale"])
        self.set_font(self.heading_font, "B", font_size)
        self.set_text_color(*self.DARK)
        display_title = title.upper() if t["title_upper"] else title

        align = t.get("title_align", "L")
        self.cell(0, 8, _safe(display_title), new_x="LMARGIN", new_y="NEXT", align=align)

        y = self.get_y()
        decoration = t.get("title_decoration", "underline")

        if decoration == "underline":
            self.set_draw_color(*self.PRIMARY)
            self.set_line_width(0.6)
            self.line(self.l_margin, y, self.w - self.r_margin, y)
            self.ln(4)
        elif decoration == "bar":
            # Left bar is handled by indenting; draw a thin line on the left
            self.set_draw_color(*self.PRIMARY)
            self.set_line_width(1.0)
            bar_x = self.l_margin
            self.line(bar_x, y - 8, bar_x, y)
            self.ln(4)
        elif decoration == "double":
            self.set_draw_color(*self.PRIMARY)
            self.set_line_width(0.6)
            self.line(self.l_margin, y, self.w - self.r_margin, y)
            self.set_line_width(0.3)
            self.line(self.l_margin, y + 1.5, self.w - self.r_margin, y + 1.5)
            self.ln(4)
        else:
            self.ln(3)

    def body_text(self, text: str, bold: bool = False):
        """Multi-cell body text."""
        if not text:
            return
        text = _safe(text)
        size = round(self.theme["body_size"] * self.theme["font_scale"])
        self.set_font(self.body_font, "B" if bold else "", size)
        self.set_text_color(*self.DARK)
        self.multi_cell(0, 5, text)
        self.ln(1)

    def label_value(self, label: str, value: str):
        """Inline label: value pair."""
        if not value:
            return
        label = _safe(label)
        value = _safe(str(value))
        size = round(self.theme["body_size"] * self.theme["font_scale"])
        self.set_font(self.body_font, "B", size)
        self.set_text_color(*self.GRAY)
        lw = self.get_string_width(label + ": ") + 2
        self.cell(lw, 5, label + ": ")
        self.set_font(self.body_font, "", size)
        self.set_text_color(*self.DARK)
        self.multi_cell(0, 5, value)
        self.ln(1)

    def bullet(self, text: str):
        """Bullet point item using theme's bullet character."""
        if not text:
            return
        text = _safe(text)
        size = round(self.theme["body_size"] * self.theme["font_scale"])
        self.set_font(self.body_font, "", size)
        self.set_text_color(*self.DARK)
        bchar = _safe(self.theme.get("bullet_char", "|"))
        self.cell(6, 5, bchar)
        self.multi_cell(0, 5, text)
        self.ln(0.5)


def generate_resume_pdf(resume: dict, mode: str = "cv") -> bytes:
    """Generate a professional PDF from resume data dict.

    mode: "resume" = single page, concise (no descriptions, key info only)
          "cv" = full detail, 1-2 pages with everything
    """
    concise = mode == "resume"

    # ── Read style from resume ────────────────────────────────────
    style = resume.get("style") or {}
    if not isinstance(style, dict):
        style = {}

    theme_id = style.get("theme", "classic")
    theme = THEMES.get(theme_id, THEMES["classic"])

    primary_hex = style.get("primaryColor", "#f5b942")
    primary_rgb = _hex_to_rgb(primary_hex)

    heading_font_family = style.get("fontHeading", "Helvetica, Arial, sans-serif")
    body_font_family = style.get("fontBody", "Helvetica, Arial, sans-serif")
    heading_font = _FONT_MAP.get(heading_font_family, "Helvetica")
    body_font = _FONT_MAP.get(body_font_family, "Helvetica")

    # ── Build PDF ─────────────────────────────────────────────────
    pdf = ResumePDF(theme, primary_rgb, heading_font, body_font)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pad = theme.get("padding", 10)
    pdf.set_margins(pad, pad, pad)

    entry_title_size = round(theme["entry_title_size"] * theme["font_scale"])
    body_size = round(theme["body_size"] * theme["font_scale"])
    entry_gap = theme["entry_gap"]
    section_gap = theme["section_gap"]

    # ── Name & Contact ────────────────────────────────────────────
    name = _safe(resume.get("full_name", "Resume"))
    name_size = round(22 * theme["font_scale"])
    pdf.set_font(heading_font, "B", name_size)
    pdf.set_text_color(*pdf.DARK)
    pdf.cell(0, 12, name or "Resume", new_x="LMARGIN", new_y="NEXT", align=theme["name_align"])

    contacts = []
    if resume.get("email"):
        contacts.append(_safe(resume["email"]))
    if resume.get("phone"):
        contacts.append(_safe(resume["phone"]))
    if resume.get("location"):
        contacts.append(_safe(resume["location"]))
    if contacts:
        pdf.set_font(body_font, "", body_size)
        pdf.set_text_color(*pdf.GRAY)
        pdf.cell(0, 5, "  |  ".join(contacts), new_x="LMARGIN", new_y="NEXT", align=theme["name_align"])

    links = []
    if resume.get("linkedin_url"):
        links.append(f"LinkedIn: {_safe(resume['linkedin_url'])}")
    if resume.get("portfolio_url"):
        links.append(f"Portfolio: {_safe(resume['portfolio_url'])}")
    if links:
        pdf.set_font(body_font, "", round(9 * theme["font_scale"]))
        pdf.set_text_color(*pdf.PRIMARY)
        pdf.cell(0, 5, "  |  ".join(links), new_x="LMARGIN", new_y="NEXT", align=theme["name_align"])

    pdf.ln(section_gap)

    # ── Summary ───────────────────────────────────────────────────
    if resume.get("summary"):
        pdf.section_title("Professional Summary")
        pdf.body_text(_safe(resume["summary"]))
        pdf.ln(section_gap * 0.5)

    # ── Education ─────────────────────────────────────────────────
    edu = resume.get("education", [])
    if edu:
        pdf.section_title("Education")
        for e in edu:
            degree_field = _safe(" ".join(filter(None, [e.get("degree"), e.get("field")])))
            inst = _safe(e.get("institution", ""))
            dates = _safe(" - ".join(filter(None, [e.get("start_date"), e.get("end_date")])))

            pdf.set_font(heading_font, "B", entry_title_size)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 6, degree_field or inst, new_x="LMARGIN", new_y="NEXT")

            if degree_field and inst:
                pdf.set_font(body_font, "", body_size)
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, inst, new_x="LMARGIN", new_y="NEXT")

            if dates:
                pdf.set_font(body_font, "I", round(9 * theme["font_scale"]))
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, dates, new_x="LMARGIN", new_y="NEXT")

            if e.get("gpa") and not concise:
                pdf.label_value("GPA", _safe(str(e["gpa"])))
            if e.get("description") and not concise:
                pdf.body_text(_safe(e["description"]))
            pdf.ln(entry_gap)

    # ── Work Experience ───────────────────────────────────────────
    exp = resume.get("experience", [])
    if exp:
        pdf.section_title("Work Experience")
        for ex in exp:
            pos = _safe(ex.get("position", ""))
            company = _safe(ex.get("company", ""))
            dates = _safe(" - ".join(filter(None, [ex.get("start_date"), ex.get("end_date")])))

            pdf.set_font(heading_font, "B", entry_title_size)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 6, pos, new_x="LMARGIN", new_y="NEXT")

            right_text = _safe(", ".join(filter(None, [company, ex.get("location")])))
            if right_text or dates:
                pdf.set_font(body_font, "", body_size)
                pdf.set_text_color(*pdf.GRAY)
                parts = [right_text, dates]
                pdf.cell(0, 5, "  |  ".join(filter(None, parts)), new_x="LMARGIN", new_y="NEXT")

            if ex.get("description") and not concise:
                pdf.body_text(_safe(ex["description"]))
            for ach in ex.get("achievements", []):
                pdf.bullet(ach)
            pdf.ln(entry_gap)

    # ── Research / Projects ───────────────────────────────────────
    projects = resume.get("research_projects", [])
    if projects:
        pdf.section_title("Research & Projects")
        for p in projects:
            ptype = _safe(p.get("type", "project").capitalize())
            title = _safe(p.get("title", ""))
            org = _safe(p.get("organization", ""))
            role = _safe(p.get("role", ""))
            dates = _safe(" - ".join(filter(None, [p.get("start_date"), p.get("end_date")])))

            pdf.set_font(heading_font, "B", entry_title_size)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 6, f"[{ptype}] {title}", new_x="LMARGIN", new_y="NEXT")

            details = " | ".join(filter(None, [role, org, dates]))
            if details:
                pdf.set_font(body_font, "", body_size)
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, details, new_x="LMARGIN", new_y="NEXT")

            if p.get("technologies"):
                pdf.set_font(body_font, "I", round(9 * theme["font_scale"]))
                pdf.cell(0, 5, f"Tech: {p['technologies']}", new_x="LMARGIN", new_y="NEXT")

            if p.get("description"):
                pdf.body_text(_safe(p["description"]))
            if p.get("outcomes"):
                pdf.label_value("Outcomes", _safe(p["outcomes"]))
            if p.get("url"):
                pdf.label_value("URL", _safe(p["url"]))
            pdf.ln(entry_gap)

    # ── Skills ────────────────────────────────────────────────────
    skills = resume.get("skills", [])
    if skills:
        pdf.section_title("Skills")
        pdf.set_font(body_font, "", body_size)
        pdf.set_text_color(*pdf.DARK)
        pdf.multi_cell(0, 5, " | ".join(skills))
        pdf.ln(section_gap)

    # ── Languages ─────────────────────────────────────────────────
    langs = resume.get("languages", [])
    if langs:
        pdf.section_title("Languages")
        for lang in langs:
            name = _safe(lang.get("language", ""))
            prof = _safe(lang.get("proficiency", ""))
            pdf.set_font(body_font, "B", body_size)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(40, 5, name)
            pdf.set_font(body_font, "", body_size)
            pdf.set_text_color(*pdf.GRAY)
            pdf.cell(0, 5, prof, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(section_gap * 0.5)

    # ── Certifications ────────────────────────────────────────────
    certs = resume.get("certifications", [])
    if certs and not concise:
        pdf.section_title("Certifications")
        for c in certs:
            name = _safe(c.get("name", ""))
            issuer = _safe(c.get("issuer", ""))
            date = _safe(c.get("date", ""))
            pdf.set_font(body_font, "B", body_size)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 5, name, new_x="LMARGIN", new_y="NEXT")
            details = " | ".join(filter(None, [issuer, date]))
            if details:
                pdf.set_font(body_font, "", round(9 * theme["font_scale"]))
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, details, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(entry_gap)

    # ── Publications ──────────────────────────────────────────────
    pubs = resume.get("publications", [])
    if pubs and not concise:
        pdf.section_title("Publications")
        for p in pubs:
            pdf.bullet(_safe(p.get("title", "")))
            details = " | ".join(filter(None, [p.get("journal"), p.get("date")]))
            if details:
                pdf.set_font(body_font, "I", round(9 * theme["font_scale"]))
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(6, 5, "")
                pdf.cell(0, 5, details, new_x="LMARGIN", new_y="NEXT")
            if p.get("doi"):
                pdf.set_font(body_font, "", round(8 * theme["font_scale"]))
                pdf.cell(6, 5, "")
                pdf.cell(0, 5, f"DOI: {_safe(p['doi'])}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(entry_gap)

    # ── Awards ────────────────────────────────────────────────────
    awards = resume.get("awards", [])
    if awards and not concise:
        pdf.section_title("Awards")
        for a in awards:
            name = _safe(a.get("name", ""))
            issuer = _safe(a.get("issuer", ""))
            date = a.get("date", "")
            details = " | ".join(filter(None, [issuer, date]))
            pdf.set_font(body_font, "B", body_size)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 5, name, new_x="LMARGIN", new_y="NEXT")
            if details:
                pdf.set_font(body_font, "", round(9 * theme["font_scale"]))
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, details, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(entry_gap)

    # ── References ────────────────────────────────────────────────
    refs = resume.get("ref_list", [])
    if refs and not concise:
        pdf.section_title("References")
        for r in refs:
            pdf.set_font(body_font, "B", body_size)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(0, 5, _safe(r.get("name", "")), new_x="LMARGIN", new_y="NEXT")
            if r.get("position"):
                pdf.set_font(body_font, "", round(9 * theme["font_scale"]))
                pdf.set_text_color(*pdf.GRAY)
                pdf.cell(0, 5, _safe(r["position"]), new_x="LMARGIN", new_y="NEXT")
            if r.get("contact"):
                pdf.set_font(body_font, "", round(9 * theme["font_scale"]))
                pdf.cell(0, 5, _safe(r["contact"]), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(entry_gap)

    return bytes(pdf.output())
