"""ISO 3166-1 alpha-2 country reference data."""

COUNTRIES = [
    ("AF", "Afghanistan", "AFG"),
    ("AL", "Albania", "ALB"),
    ("DZ", "Algeria", "DZA"),
    ("AS", "American Samoa", "ASM"),
    ("AD", "Andorra", "AND"),
    ("AO", "Angola", "AGO"),
    ("AI", "Anguilla", "AIA"),
    ("AQ", "Antarctica", "ATA"),
    ("AG", "Antigua and Barbuda", "ATG"),
    ("AR", "Argentina", "ARG"),
    ("AM", "Armenia", "ARM"),
    ("AW", "Aruba", "ABW"),
    ("AU", "Australia", "AUS"),
    ("AT", "Austria", "AUT"),
    ("AZ", "Azerbaijan", "AZE"),
    ("BS", "Bahamas", "BHS"),
    ("BH", "Bahrain", "BHR"),
    ("BD", "Bangladesh", "BGD"),
    ("BB", "Barbados", "BRB"),
    ("BY", "Belarus", "BLR"),
    ("BE", "Belgium", "BEL"),
    ("BZ", "Belize", "BLZ"),
    ("BJ", "Benin", "BEN"),
    ("BM", "Bermuda", "BMU"),
    ("BT", "Bhutan", "BTN"),
    ("BO", "Bolivia", "BOL"),
    ("BA", "Bosnia and Herzegovina", "BIH"),
    ("BW", "Botswana", "BWA"),
    ("BR", "Brazil", "BRA"),
    ("BN", "Brunei", "BRN"),
    ("BG", "Bulgaria", "BGR"),
    ("BF", "Burkina Faso", "BFA"),
    ("BI", "Burundi", "BDI"),
    ("CV", "Cabo Verde", "CPV"),
    ("KH", "Cambodia", "KHM"),
    ("CM", "Cameroon", "CMR"),
    ("CA", "Canada", "CAN"),
    ("KY", "Cayman Islands", "CYM"),
    ("CF", "Central African Republic", "CAF"),
    ("TD", "Chad", "TCD"),
    ("CL", "Chile", "CHL"),
    ("CN", "China", "CHN"),
    ("CO", "Colombia", "COL"),
    ("KM", "Comoros", "COM"),
    ("CG", "Congo", "COG"),
    ("CD", "Congo (Democratic Republic)", "COD"),
    ("CK", "Cook Islands", "COK"),
    ("CR", "Costa Rica", "CRI"),
    ("CI", "Cote d'Ivoire", "CIV"),
    ("HR", "Croatia", "HRV"),
    ("CU", "Cuba", "CUB"),
    ("CW", "Curacao", "CUW"),
    ("CY", "Cyprus", "CYP"),
    ("CZ", "Czech Republic", "CZE"),
    ("DK", "Denmark", "DNK"),
    ("DJ", "Djibouti", "DJI"),
    ("DM", "Dominica", "DMA"),
    ("DO", "Dominican Republic", "DOM"),
    ("EC", "Ecuador", "ECU"),
    ("EG", "Egypt", "EGY"),
    ("SV", "El Salvador", "SLV"),
    ("GQ", "Equatorial Guinea", "GNQ"),
    ("ER", "Eritrea", "ERI"),
    ("EE", "Estonia", "EST"),
    ("SZ", "Eswatini", "SWZ"),
    ("ET", "Ethiopia", "ETH"),
    ("FK", "Falkland Islands", "FLK"),
    ("FO", "Faroe Islands", "FRO"),
    ("FJ", "Fiji", "FJI"),
    ("FI", "Finland", "FIN"),
    ("FR", "France", "FRA"),
    ("GA", "Gabon", "GAB"),
    ("GM", "Gambia", "GMB"),
    ("GE", "Georgia", "GEO"),
    ("DE", "Germany", "DEU"),
    ("GH", "Ghana", "GHA"),
    ("GI", "Gibraltar", "GIB"),
    ("GR", "Greece", "GRC"),
    ("GL", "Greenland", "GRL"),
    ("GD", "Grenada", "GRD"),
    ("GP", "Guadeloupe", "GLP"),
    ("GU", "Guam", "GUM"),
    ("GT", "Guatemala", "GTM"),
    ("GG", "Guernsey", "GGY"),
    ("GN", "Guinea", "GIN"),
    ("GW", "Guinea-Bissau", "GNB"),
    ("GY", "Guyana", "GUY"),
    ("HT", "Haiti", "HTI"),
    ("HN", "Honduras", "HND"),
    ("HK", "Hong Kong", "HKG"),
    ("HU", "Hungary", "HUN"),
    ("IS", "Iceland", "ISL"),
    ("IN", "India", "IND"),
    ("ID", "Indonesia", "IDN"),
    ("IR", "Iran", "IRN"),
    ("IQ", "Iraq", "IRQ"),
    ("IE", "Ireland", "IRL"),
    ("IM", "Isle of Man", "IMN"),
    ("IL", "Israel", "ISR"),
    ("IT", "Italy", "ITA"),
    ("JM", "Jamaica", "JAM"),
    ("JP", "Japan", "JPN"),
    ("JE", "Jersey", "JEY"),
    ("JO", "Jordan", "JOR"),
    ("KZ", "Kazakhstan", "KAZ"),
    ("KE", "Kenya", "KEN"),
    ("KI", "Kiribati", "KIR"),
    ("KP", "North Korea", "PRK"),
    ("KR", "South Korea", "KOR"),
    ("KW", "Kuwait", "KWT"),
    ("KG", "Kyrgyzstan", "KGZ"),
    ("LA", "Laos", "LAO"),
    ("LV", "Latvia", "LVA"),
    ("LB", "Lebanon", "LBN"),
    ("LS", "Lesotho", "LSO"),
    ("LR", "Liberia", "LBR"),
    ("LY", "Libya", "LBY"),
    ("LI", "Liechtenstein", "LIE"),
    ("LT", "Lithuania", "LTU"),
    ("LU", "Luxembourg", "LUX"),
    ("MO", "Macao", "MAC"),
    ("MG", "Madagascar", "MDG"),
    ("MW", "Malawi", "MWI"),
    ("MY", "Malaysia", "MYS"),
    ("MV", "Maldives", "MDV"),
    ("ML", "Mali", "MLI"),
    ("MT", "Malta", "MLT"),
    ("MH", "Marshall Islands", "MHL"),
    ("MQ", "Martinique", "MTQ"),
    ("MR", "Mauritania", "MRT"),
    ("MU", "Mauritius", "MUS"),
    ("YT", "Mayotte", "MYT"),
    ("MX", "Mexico", "MEX"),
    ("FM", "Micronesia", "FSM"),
    ("MD", "Moldova", "MDA"),
    ("MC", "Monaco", "MCO"),
    ("MN", "Mongolia", "MNG"),
    ("ME", "Montenegro", "MNE"),
    ("MS", "Montserrat", "MSR"),
    ("MA", "Morocco", "MAR"),
    ("MZ", "Mozambique", "MOZ"),
    ("MM", "Myanmar", "MMR"),
    ("NA", "Namibia", "NAM"),
    ("NR", "Nauru", "NRU"),
    ("NP", "Nepal", "NPL"),
    ("NL", "Netherlands", "NLD"),
    ("NC", "New Caledonia", "NCL"),
    ("NZ", "New Zealand", "NZL"),
    ("NI", "Nicaragua", "NIC"),
    ("NE", "Niger", "NER"),
    ("NG", "Nigeria", "NGA"),
    ("NU", "Niue", "NIU"),
    ("NF", "Norfolk Island", "NFK"),
    ("MK", "North Macedonia", "MKD"),
    ("MP", "Northern Mariana Islands", "MNP"),
    ("NO", "Norway", "NOR"),
    ("OM", "Oman", "OMN"),
    ("PK", "Pakistan", "PAK"),
    ("PW", "Palau", "PLW"),
    ("PS", "Palestine", "PSE"),
    ("PA", "Panama", "PAN"),
    ("PG", "Papua New Guinea", "PNG"),
    ("PY", "Paraguay", "PRY"),
    ("PE", "Peru", "PER"),
    ("PH", "Philippines", "PHL"),
    ("PL", "Poland", "POL"),
    ("PT", "Portugal", "PRT"),
    ("PR", "Puerto Rico", "PRI"),
    ("QA", "Qatar", "QAT"),
    ("RE", "Reunion", "REU"),
    ("RO", "Romania", "ROU"),
    ("RU", "Russia", "RUS"),
    ("RW", "Rwanda", "RWA"),
    ("BL", "Saint Barthelemy", "BLM"),
    ("SH", "Saint Helena", "SHN"),
    ("KN", "Saint Kitts and Nevis", "KNA"),
    ("LC", "Saint Lucia", "LCA"),
    ("MF", "Saint Martin", "MAF"),
    ("PM", "Saint Pierre and Miquelon", "SPM"),
    ("VC", "Saint Vincent and the Grenadines", "VCT"),
    ("WS", "Samoa", "WSM"),
    ("SM", "San Marino", "SMR"),
    ("ST", "Sao Tome and Principe", "STP"),
    ("SA", "Saudi Arabia", "SAU"),
    ("SN", "Senegal", "SEN"),
    ("RS", "Serbia", "SRB"),
    ("SC", "Seychelles", "SYC"),
    ("SL", "Sierra Leone", "SLE"),
    ("SG", "Singapore", "SGP"),
    ("SX", "Sint Maarten", "SXM"),
    ("SK", "Slovakia", "SVK"),
    ("SI", "Slovenia", "SVN"),
    ("SB", "Solomon Islands", "SLB"),
    ("SO", "Somalia", "SOM"),
    ("ZA", "South Africa", "ZAF"),
    ("GS", "South Georgia", "SGS"),
    ("SS", "South Sudan", "SSD"),
    ("ES", "Spain", "ESP"),
    ("LK", "Sri Lanka", "LKA"),
    ("SD", "Sudan", "SDN"),
    ("SR", "Suriname", "SUR"),
    ("SE", "Sweden", "SWE"),
    ("CH", "Switzerland", "CHE"),
    ("SY", "Syria", "SYR"),
    ("TW", "Taiwan", "TWN"),
    ("TJ", "Tajikistan", "TJK"),
    ("TZ", "Tanzania", "TZA"),
    ("TH", "Thailand", "THA"),
    ("TL", "Timor-Leste", "TLS"),
    ("TG", "Togo", "TGO"),
    ("TK", "Tokelau", "TKL"),
    ("TO", "Tonga", "TON"),
    ("TT", "Trinidad and Tobago", "TTO"),
    ("TN", "Tunisia", "TUN"),
    ("TR", "Turkey", "TUR"),
    ("TM", "Turkmenistan", "TKM"),
    ("TC", "Turks and Caicos Islands", "TCA"),
    ("TV", "Tuvalu", "TUV"),
    ("UG", "Uganda", "UGA"),
    ("UA", "Ukraine", "UKR"),
    ("AE", "United Arab Emirates", "ARE"),
    ("GB", "United Kingdom", "GBR"),
    ("US", "United States", "USA"),
    ("UY", "Uruguay", "URY"),
    ("UZ", "Uzbekistan", "UZB"),
    ("VU", "Vanuatu", "VUT"),
    ("VE", "Venezuela", "VEN"),
    ("VN", "Vietnam", "VNM"),
    ("VG", "Virgin Islands (British)", "VGB"),
    ("VI", "Virgin Islands (U.S.)", "VIR"),
    ("WF", "Wallis and Futuna", "WLF"),
    ("EH", "Western Sahara", "ESH"),
    ("YE", "Yemen", "YEM"),
    ("ZM", "Zambia", "ZMB"),
    ("ZW", "Zimbabwe", "ZWE"),
]
