"""Initial country groups for scholarship eligibility.

Each group has a real source URL and source date. Membership lists are
explicit ISO 3166-1 alpha-2 codes — no formulas or "all except" logic.
"""

INITIAL_GROUPS = {
    "EU": {
        "name": "European Union",
        "description": "EU member states as of 2024.",
        "source_url": "https://european-union.europa.eu/principles-countries-history/country-profiles_en",
        "source_date": "2024-01-01",
        "members": [
            "AT",
            "BE",
            "BG",
            "HR",
            "CY",
            "CZ",
            "DK",
            "EE",
            "FI",
            "FR",
            "DE",
            "GR",
            "HU",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MT",
            "NL",
            "PL",
            "PT",
            "RO",
            "SK",
            "SI",
            "ES",
            "SE"
        ]
    },
    "EEA": {
        "name": "European Economic Area",
        "description": "EU members plus Iceland, Liechtenstein, and Norway.",
        "source_url": "https://www.eea.europa.eu/en/about-us",
        "source_date": "2024-01-01",
        "members": [
            "AT",
            "BE",
            "BG",
            "HR",
            "CY",
            "CZ",
            "DK",
            "EE",
            "FI",
            "FR",
            "DE",
            "GR",
            "HU",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MT",
            "NL",
            "PL",
            "PT",
            "RO",
            "SK",
            "SI",
            "ES",
            "SE",
            "IS",
            "LI",
            "NO"
        ]
    },
    "COMMONWEALTH": {
        "name": "Commonwealth of Nations",
        "description": "Member states of the Commonwealth of Nations.",
        "source_url": "https://thecommonwealth.org/our-member-countries",
        "source_date": "2024-01-01",
        "members": [
            "AG",
            "AU",
            "BS",
            "BD",
            "BB",
            "BZ",
            "BW",
            "BN",
            "CM",
            "CA",
            "CY",
            "DM",
            "FJ",
            "GM",
            "GH",
            "GD",
            "GY",
            "IN",
            "JM",
            "KE",
            "KI",
            "LS",
            "MW",
            "MY",
            "MV",
            "MT",
            "MU",
            "MZ",
            "NA",
            "NR",
            "NZ",
            "NG",
            "PK",
            "PG",
            "RW",
            "KN",
            "LC",
            "VC",
            "WS",
            "SC",
            "SL",
            "SG",
            "SB",
            "ZA",
            "LK",
            "SZ",
            "TZ",
            "TO",
            "TT",
            "TV",
            "UG",
            "GB",
            "VU",
            "ZM"
        ]
    },
    "OECD": {
        "name": "OECD Member Countries",
        "description": "Organisation for Economic Co-operation and Development members.",
        "source_url": "https://www.oecd.org/en/about/members.html",
        "source_date": "2024-01-01",
        "members": [
            "AU",
            "AT",
            "BE",
            "CA",
            "CL",
            "CO",
            "CR",
            "CZ",
            "DK",
            "EE",
            "FI",
            "FR",
            "DE",
            "GR",
            "HU",
            "IS",
            "IE",
            "IL",
            "IT",
            "JP",
            "KR",
            "LV",
            "LT",
            "LU",
            "MX",
            "NL",
            "NZ",
            "NO",
            "PL",
            "PT",
            "SK",
            "SI",
            "ES",
            "SE",
            "CH",
            "TR",
            "GB",
            "US"
        ]
    },
    "ASEAN": {
        "name": "ASEAN Member States",
        "description": "Association of Southeast Asian Nations members.",
        "source_url": "https://asean.org/our-member-states/",
        "source_date": "2024-01-01",
        "members": [
            "BN",
            "KH",
            "ID",
            "LA",
            "MY",
            "MM",
            "PH",
            "SG",
            "TH",
            "VN"
        ]
    },
    "AU": {
        "name": "African Union",
        "description": "All member states of the African Union.",
        "source_url": "https://au.int/en/member_states",
        "source_date": "2024-01-01",
        "members": [
            "DZ",
            "AO",
            "BJ",
            "BW",
            "BF",
            "BI",
            "CV",
            "CM",
            "CF",
            "TD",
            "KM",
            "CG",
            "CD",
            "CI",
            "DJ",
            "EG",
            "GQ",
            "ER",
            "SZ",
            "ET",
            "GA",
            "GM",
            "GH",
            "GN",
            "GW",
            "KE",
            "LS",
            "LR",
            "LY",
            "MG",
            "MW",
            "ML",
            "MR",
            "MU",
            "MA",
            "MZ",
            "NA",
            "NE",
            "NG",
            "RW",
            "ST",
            "SN",
            "SC",
            "SL",
            "SO",
            "ZA",
            "SS",
            "SD",
            "TZ",
            "TG",
            "TN",
            "UG",
            "ZM",
            "ZW"
        ]
    },
    "ECOWAS": {
        "name": "ECOWAS Member States",
        "description": "Economic Community of West African States.",
        "source_url": "https://ecowas.int/about-ecowas/member-states/",
        "source_date": "2024-01-01",
        "members": [
            "BJ",
            "BF",
            "CV",
            "GM",
            "GH",
            "GN",
            "GW",
            "CI",
            "LR",
            "ML",
            "MR",
            "NE",
            "NG",
            "SN",
            "SL",
            "TG"
        ]
    },
    "ARAB_LEAGUE": {
        "name": "Arab League Member States",
        "description": "League of Arab States members.",
        "source_url": "https://www.lasportal.org/en/aboutlas/Pages/MemberStates.aspx",
        "source_date": "2024-01-01",
        "members": [
            "DZ",
            "BH",
            "KM",
            "DJ",
            "EG",
            "IQ",
            "JO",
            "KW",
            "LB",
            "LY",
            "MR",
            "MA",
            "OM",
            "PS",
            "QA",
            "SA",
            "SO",
            "SD",
            "SY",
            "TN",
            "AE",
            "YE"
        ]
    },
    "SAARC": {
        "name": "SAARC Member States",
        "description": "South Asian Association for Regional Cooperation members.",
        "source_url": "https://saarc-sec.org/member-states/",
        "source_date": "2024-01-01",
        "members": [
            "AF",
            "BD",
            "BT",
            "IN",
            "MV",
            "NP",
            "PK",
            "LK"
        ]
    },
    "NIIED": {
        "name": "NIIED/GKS-Eligible Countries",
        "description": "Countries eligible for Korean Government Scholarship (GKS) via NIIED. Excludes South Korea (host). Based on the annual GKS announcement \u2014 typically open to all countries except the host.",
        "source_url": "https://www.studyinkorea.go.kr/en/sub/gks/all_scholarship.do",
        "source_date": "2024-03-01",
        "members": [
            "AF",
            "AL",
            "DZ",
            "AD",
            "AO",
            "AG",
            "AR",
            "AM",
            "AU",
            "AT",
            "AZ",
            "BS",
            "BH",
            "BD",
            "BB",
            "BY",
            "BE",
            "BZ",
            "BJ",
            "BT",
            "BO",
            "BA",
            "BW",
            "BR",
            "BN",
            "BG",
            "BF",
            "BI",
            "CV",
            "KH",
            "CM",
            "CA",
            "CF",
            "TD",
            "CL",
            "CN",
            "CO",
            "KM",
            "CG",
            "CD",
            "CR",
            "CI",
            "HR",
            "CU",
            "CY",
            "CZ",
            "DK",
            "DJ",
            "DM",
            "DO",
            "EC",
            "EG",
            "SV",
            "GQ",
            "ER",
            "EE",
            "SZ",
            "ET",
            "FJ",
            "FI",
            "FR",
            "GA",
            "GM",
            "GE",
            "DE",
            "GH",
            "GR",
            "GD",
            "GT",
            "GN",
            "GW",
            "GY",
            "HT",
            "HN",
            "HU",
            "IS",
            "IN",
            "ID",
            "IR",
            "IQ",
            "IE",
            "IL",
            "IT",
            "JM",
            "JP",
            "JO",
            "KZ",
            "KE",
            "KI",
            "KP",
            "KW",
            "KG",
            "LA",
            "LV",
            "LB",
            "LS",
            "LR",
            "LY",
            "LI",
            "LT",
            "LU",
            "MG",
            "MW",
            "MY",
            "MV",
            "ML",
            "MT",
            "MH",
            "MR",
            "MU",
            "MX",
            "FM",
            "MD",
            "MC",
            "MN",
            "ME",
            "MA",
            "MZ",
            "MM",
            "NA",
            "NR",
            "NP",
            "NL",
            "NZ",
            "NI",
            "NE",
            "NG",
            "MK",
            "NO",
            "OM",
            "PK",
            "PW",
            "PA",
            "PG",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "QA",
            "RO",
            "RU",
            "RW",
            "KN",
            "LC",
            "VC",
            "WS",
            "SM",
            "ST",
            "SA",
            "SN",
            "RS",
            "SC",
            "SL",
            "SG",
            "SK",
            "SI",
            "SB",
            "SO",
            "ZA",
            "SS",
            "ES",
            "LK",
            "SD",
            "SR",
            "SE",
            "CH",
            "SY",
            "TJ",
            "TZ",
            "TH",
            "TL",
            "TG",
            "TO",
            "TT",
            "TN",
            "TR",
            "TM",
            "TV",
            "UG",
            "UA",
            "AE",
            "GB",
            "US",
            "UY",
            "UZ",
            "VU",
            "VE",
            "VN",
            "YE",
            "ZM",
            "ZW"
        ]
    },
    "ERASMUS_PARTNER": {
        "name": "Erasmus Mundus Partner Countries",
        "description": "Countries classified as Partner Countries for Erasmus Mundus Joint Masters (non-EU/EEA/UK).",
        "source_url": "https://erasmus-plus.ec.europa.eu/programme-guide/part-b/key-action-1/emjm",
        "source_date": "2024-01-01",
        "members": [
            "AF",
            "DZ",
            "AZ",
            "BH",
            "BD",
            "BT",
            "BN",
            "KH",
            "CM",
            "CV",
            "CF",
            "TD",
            "CN",
            "CO",
            "KM",
            "CG",
            "CD",
            "CR",
            "CI",
            "CU",
            "DJ",
            "DM",
            "DO",
            "EC",
            "EG",
            "SV",
            "GQ",
            "ER",
            "SZ",
            "ET",
            "FJ",
            "GA",
            "GM",
            "GE",
            "GH",
            "GD",
            "GT",
            "GN",
            "GW",
            "GY",
            "HT",
            "HN",
            "IN",
            "ID",
            "IR",
            "IQ",
            "JM",
            "JO",
            "KZ",
            "KE",
            "KI",
            "KP",
            "KR",
            "KW",
            "KG",
            "LA",
            "LB",
            "LS",
            "LR",
            "LY",
            "MG",
            "MW",
            "MY",
            "MV",
            "ML",
            "MH",
            "MR",
            "MU",
            "MX",
            "FM",
            "MD",
            "MN",
            "ME",
            "MA",
            "MZ",
            "MM",
            "NA",
            "NR",
            "NP",
            "NI",
            "NE",
            "NG",
            "MK",
            "OM",
            "PK",
            "PW",
            "PA",
            "PG",
            "PY",
            "PE",
            "PH",
            "QA",
            "RO",
            "RU",
            "RW",
            "KN",
            "LC",
            "VC",
            "WS",
            "ST",
            "SA",
            "SN",
            "RS",
            "SC",
            "SL",
            "SG",
            "SB",
            "SO",
            "ZA",
            "SS",
            "LK",
            "SD",
            "SR",
            "SY",
            "TJ",
            "TZ",
            "TH",
            "TL",
            "TG",
            "TO",
            "TT",
            "TN",
            "TR",
            "TM",
            "TV",
            "UG",
            "UA",
            "AE",
            "US",
            "UY",
            "UZ",
            "VU",
            "VE",
            "VN",
            "YE",
            "ZM",
            "ZW"
        ]
    }
}
